### ISSUE TITLE
Is this library replaced by mxparser?

### ISSUE THREAD

**Issue by Kyson** [mtrakal/jeval#1]
jeval homepage http://jeval.sourceforge.net/ not found , instead of  https://sourceforge.net/projects/mxparser/

Is this library replaced by mxparser?

**Comment by mtrakal** [comment]
🤷‍♂️ have no idea, I don't use jeval anymore in any of my project for years

**Comment by greek1979** [comment]
@Kyson , to my knowledge and understanding, Mxparser is NOT a direct replacement for old jeval library, although it can do most of the things jeval did in the past. Even the source code differs completely, so while some ideas may have been loaned from jeval, the rest is new invention. And while we are on this topic, I welcome you to take a look at my jeval fork https://github.com/greek1979/jeval with lots of updates (new expression functions, fixes to syntax and parse engine, etc.). My company does use jeval for historic reasons, and probably will to do for the foreseeable future; as jeval was originally published under Apache License 2.0, I resorted to making all our improvements to jeval public at GitHub.
